# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider :hyperv do |v|
        v.vmname  = "http-shell" 
    end

    config.vm.hostname = "http-shell"
    config.vm.network "public_network"
    config.vm.provider "hyperv"
    config.vm.box = "generic/ubuntu2004"
    config.vm.synced_folder "./../../", "/vagrant", type: "smb"
    config.vm.provision :shell, path: "./../provision.sh"

    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8081, host: 8081
    
end