# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = "http-shell"
    config.vm.synced_folder "./../..", "/vagrant", type: "nfs"
    config.vm.provision :shell, path: "./../provision.sh"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "forwarded_port", guest: 8081, host: 8081
  
    config.vm.provider :libvirt do |v|
       v.default_prefix = "http-shell"
    end
  
  end
  